# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-jenkin-demo-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: python-jenkin-demo
  template:
    metadata:
      labels:
        app: python-jenkin-demo
    spec:
      containers:
        - name: python-jenkin-demo
          image: gpalve/python-jenkin-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-jenkin-demo-service
spec:
  selector:
    app: python-jenkin-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer  # Change this to LoadBalancer if Minikube supports LoadBalancer
